### ISSUE TITLE
Error upgrading to 0.5.0

### ISSUE THREAD

**Issue by johnhaley81** [wmayner/pyemd#27] opened 2018-01-26 16:07 UTC
When trying to upgrade to 0.5.0 I'm getting the following output:

```
Collecting pyemd
  Using cached pyemd-0.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-odst_5et/pyemd/setup.py", line 87, in <module>
        README = f.read()
      File "/srv/.pyenv/versions/3.6.3/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2247: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-odst_5et/pyemd/
```

Seems like there's an issue with decoding a file. Shouldn't unicode be used instead of ascii? Is this an issue with my system configuration?

Thanks!

**Comment by johnhaley81** [comment] 2018-01-26 16:37
I checked what encoding python3 is using on my system and this is what I get:

```
root@9cb226d9f4f0:/root# python3 -c 'import sys; print(sys.stdin.encoding, sys.stdout.encoding)'
utf-8 utf-8
root@9cb226d9f4f0:/root# python3 -c 'import sys; print(sys.getdefaultencoding())'
utf-8
```

**Comment by wmayner** [comment] 2018-01-26 18:46
Thanks for the report. I remember something similar happening with a previous release. It must be system-specific, since I don't have this issue on my machines and the Travis build checks out. But in any case, a quick fix would be to remove the non-ASCII character from line 81 of the README and push a new release.

**Comment by wmayner** [comment] 2018-01-28 00:24
I pushed what I think is a fix—since I can't reproduce this, would you try installing from the develop branch with `pip install --upgrade "git+https://github.com/wmayner/pyemd.git"`?

**Comment by johnhaley81** [comment] 2018-01-28 04:01
It's fixed! 🎉

**Comment by wmayner** [comment] 2018-01-29 04:17
Fixed in v0.5.1.

**Closed by wmayner** 2018-01-29 04:17 UTC

**Comment by waterbeach** [comment] 2018-06-05 14:22
v0.5.1 still have this problem

**Comment by wmayner** [comment] 2018-06-05 16:19
Give me more information, please.
